# Generated by Django 2.2.1 on 2019-05-14 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0001_initial")]

    operations = [
        migrations.AlterModelOptions(
            name="post", options={"ordering": ["-publish_at"]}
        ),
        migrations.RemoveField(model_name="post", name="date_to_publish"),
        migrations.AddField(
            model_name="post",
            name="publish_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="post", name="post_title", field=models.CharField(max_length=100)
        ),
    ]
