# Generated by Django 2.2.1 on 2019-05-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0002_auto_20190513_2239")]

    operations = [
        migrations.AddField(
            model_name="post",
            name="rating",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="post",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
