# Generated by Django 2.2.1 on 2019-05-23 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("posts", "0004_auto_20190521_1816")]

    operations = [
        migrations.RemoveField(model_name="post", name="synopsis"),
        migrations.AddField(
            model_name="book",
            name="synopsis",
            field=models.TextField(blank=True, null=True),
        ),
    ]
